# Generated by Django 5.0.6 on 2024-05-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gulproduct',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='gulproduct',
            name='image',
            field=models.ImageField(default='default_img/default_book_img.png', upload_to='media/'),
        ),
    ]
