# Generated by Django 5.0.6 on 2024-05-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_gulproduct_created_at_alter_gulproduct_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatafsilMalumot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'batafsil_malumot',
            },
        ),
    ]
