# Generated by Django 5.0.6 on 2024-05-21 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_batafsilmalumot'),
    ]

    operations = [
        migrations.AddField(
            model_name='batafsilmalumot',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.gulproduct'),
            preserve_default=False,
        ),
    ]
