# Generated by Django 5.0.6 on 2024-05-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_batafsilmalumot_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gulproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
